## Put comments here that give an overall description of what your
## functions do

## Takes a matrix as its argument and creates a list of 4 functions
## get, getinverse and setinverse should be called from cacheSolve func
## Example call: a <- makeCacheMatrix(matrix(c(4,2,7,6), nrow = 2, ncol = 2))

makeCacheMatrix <- function(x = matrix()) {
        matrix_inverse <- NULL
        ## 1st function: assigns argument 'y' to matrix value (overwrites existing) and nulls the inverse value
        ## Example call: a$set(matrix(c(2,2,3,2), nrow = 2, ncol = 2))
        set <- function(y) {
                x <<- y
                matrix_inverse <<- NULL
        }
        ## 2nd function: returns the existing value of m (matrix). Example call: a$get()
        get <- function() x
        ## 3rd function: simply assigns argument 'inverse' to the value of the matrix_inverse (overwrites existing value)
        ## Example call:  a$setinverse(10) - should be called by cacheSolve function
        setinverse <- function(inverse) matrix_inverse <<- inverse
        ## 4th function: returns the existing value of matrix_inverse. Example call: a$getinverse()
        getinverse <- function() matrix_inverse
        ## final list of functions generated by this function
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)

}

## Takes a list of functions created by makeCacheMatrix as its arguments and checks for existing 'matrix_inverse' to returns
## Else gets the matrix value m and uses solve function to compute inverse. Sets matrix_inverse to this computed value

## Example call. First call makeCacheMatrix to create the list:
## a <- makeCacheMatrix(matrix(c(4,2,7,6), nrow = 2, ncol = 2))
## cacheSolve(a)
## a$getinverse()
## above example should return:
##      [,1] [,2]
## [1,]  0.6 -0.7
## [2,] -0.2  0.4

cacheSolve <- function(x, ...) {
## check for an existing value created by makeCacheMatrix
        m <- x$getinverse()
        if(!is.null(m)) {   ## if it's not null, return it
                message("getting cached data")
                return(m)
        }
        data <- x$get() ## get the matrix value from makeCacheMatrix
        m <- solve(data, ...) ## compute inverse matrix with solve function
        x$setinverse(m) ## call setinverse function (from makeCacheMatrix) to store result
        m
        ## Return a matrix that is the inverse of 'x'
}
